#!/usr/bin/env python
import os
import logging
import shutil
import pymongo

DB = 'mstar2'
COLLECTION = 'targets'
VALIDATION_PATH = '/projects/jupiter8/data/validation'
NUM_VALID = 24

CLASSES = ['BMP2', 'BTR70', 'T72', 'D7', 'T62', '2S1', 'BRDM_2', 'ZIL131', 'ZSU_23_4', 'SLICY']

client = pymongo.MongoClient()

log = logging.getLogger(__name__)

def main():
    for klass in CLASSES:
        new_dir = os.path.join(VALIDATION_PATH, klass)
        if not os.path.exists(new_dir): os.mkdir(new_dir)
        query = {'target_class': klass, 'label': 'train'}
        cursor = client[DB][COLLECTION].find(query)
        documents = cursor[:NUM_VALID]
        for doc in documents:
            _id = doc['_id']
            old_name = doc['filename']
            new_name = os.path.basename(old_name)
            new_name = os.path.join(new_dir, new_name)
            try:
                shutil.move(old_name, new_name)
            except:
                raise
            else:
                log.info("moved %s to %s" % (old_name, new_name))
            client[DB][COLLECTION].update({'_id': _id}, {'$set': {'filename': new_name, 'label': 'validation'}})
    return

if __name__ == '__main__':
    logging.basicConfig(level=10)
    main()
