#!/usr/bin/env python
import os
import shutil
import pymongo

OLD_DB = 'mstar'
NEW_DB = 'mstar2'
TRAIN_PATH = '/projects/jupiter8/data/train'
TEST_PATH = '/projects/jupiter8/data/test'

client = pymongo.MongoClient()

def main():
    documents = []

    train_data = client[OLD_DB]['targets'].find({'depression_angle': '15_DEG'})
    for doc in train_data:
        doc.pop('_id')
        klass = doc['target_class']
        dest = os.path.join(TRAIN_PATH, klass)
        f = os.path.basename(doc['filename'])
        new_filename = os.path.join(dest, f)
        shutil.copy(doc['filename'], new_filename)
        doc['filename'] = new_filename
        doc['label'] = 'train'
        documents.append(doc)

    test_data = client[OLD_DB]['targets'].find({'depression_angle': '17_DEG'})
    for doc in test_data:
        doc.pop('_id')
        klass = doc['target_class']
        dest = os.path.join(TEST_PATH, klass)
        f = os.path.basename(doc['filename'])
        new_filename = os.path.join(dest, f)
        shutil.copy(doc['filename'], new_filename)
        doc['filename'] = new_filename
        doc['label'] = 'test'
        documents.append(doc)

    for doc in documents:
        client[NEW_DB]['targets'].insert(doc)
    return

if __name__ == '__main__':
    main()
