#!/usr/bin/env python
# Standard imports
import os
import sys
import argparse
import json

# External dependencies
import pandas as pd
import matplotlib.pyplot as plt

# Local imports
from utils.argutils import valid_path

LOG_FILE = 'training_results.log'


def get_parser():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('indir', type=valid_path,
        help="""Directory containing training log file""")
    parser.add_argument('--outdir', type=valid_path, default=None,
        help="""Directory to save plots to""")
    return parser


def main(args):
    logfn = os.path.join(args.indir, LOG_FILE)
    df = pd.read_json(logfn)
    fig, (ax1, ax2, ax3) = plt.subplots(3,1)
    fig.suptitle('Training Results')
    # Plot accuracy
    df.plot(x='epoch', y=['d_accuracy'], ax=ax1, grid=True)
    ax1.set_xlabel('')
    ax1.set_ylabel('accuracy')
    # Plot loss
    df.plot(x='epoch', y=['d_loss', 'g_loss'], ax=ax2, grid=True)
    ax2.set_xlabel('')
    ax2.set_ylabel('loss')
    # Plot loss variance
    df.plot(x='epoch', y=['d_loss_var', 'g_loss_var'], ax=ax3, grid=True)
    ax3.set_ylabel('loss variance')

    # Save plot
    if args.outdir:
        inpath = os.path.basename(os.path.abspath(args.indir))
        fname = '.'.join((inpath, 'png'))
        fname = os.path.join(args.outdir, fname)
        plt.savefig(fname)

    plt.show()

    return

if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    main(args)
    exit(0)
