#!/usr/bin/env python
# Standard imports
import os
import sys
import argparse
import json

# External dependencies
import pandas as pd
import matplotlib.pyplot as plt

# Local imports
from utils.argutils import valid_path

LOG_FILE = 'training_results.log'
PLOT_FILE = 'training.png'


def get_parser():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('indir', type=valid_path,
        help="""Directory containing training log file""")
    parser.add_argument('-s', '--save', action='store_true',
        help="""Save plots""")
    parser.add_argument('--outdir', type=valid_path, default=None,
        help="""Directory to save plots to (uses indir if None)""")
    return parser


def main(args):
    logfn = os.path.join(args.indir, LOG_FILE)
    df = pd.read_json(logfn)
    fig, axes = plt.subplots(3,1)
    fig.suptitle('Training Results')
    # Plot accuracy
    df.plot(x='epoch', y=['d_accuracy'], ax=axes[0], grid=True)
    axes[0].set_xlabel('')
    # Plot loss
    df.plot(x='epoch', y=['d_loss', 'g_loss'], ax=axes[1], grid=True)
    axes[1].set_xlabel('')
    # Plot loss variance
    df.plot(x='epoch', y=['d_loss_var', 'g_loss_var'], ax=axes[2], grid=True)

    # Save plot
    if args.save:
        if args.outdir: outdir = args.outdir
        else: outdir = args.indir
        fname = os.path.join(outdir, PLOT_FILE)
        plt.savefig(fname)

    plt.show()

    return

if __name__ == '__main__':
    parser = get_parser()
    args = parser.parse_args()
    main(args)
    exit(0)
